# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36850b9259a54bf9008abec51838f7b0affea982ebd99e1002f76b511b11cc4a708c21e36d61768967ce36df98ade95b7c8333d0d525c3dd40e252423bdd7d4d

test:
  secret_key_base: f292f557373461e5744c1e7c3579d3931e60c2845151e4888caf0bf967334475469567533dffb6ae61f2b24d36a35c5ef690692832074654c90e2615bf458053

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
